In [48]:
import numpy as np

In [49]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [50]:
type(arr1)

numpy.ndarray

In [51]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [53]:
arr4 = np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [54]:
arr5 = np.identity((5))
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [55]:
arr6 = np.arange(1,15,2) # np.arange(5,15), np.arange(10)
arr6

array([ 1,  3,  5,  7,  9, 11, 13])

In [56]:
arr7 = np.linspace(10,20,10)
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [57]:
arr8 = np.copy(arr7)
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [58]:
arr9 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [59]:
arr9.shape


(2, 2, 2)

In [60]:
arr9.ndim

3

In [61]:
arr9.size #number of elements

8

In [62]:
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [63]:
arr9.itemsize #float -8

8

In [64]:
arr8.itemsize # size of 1 element in byte

8

In [65]:
arr9.dtype

dtype('int64')

In [66]:
arr8.dtype

dtype('float64')

In [67]:
arr9.astype('float')     # CONVERT INT to Float

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [68]:
arr9.dtype

dtype('int64')

In [69]:
lista =range(100)
arr11 = np.arange(100)

In [70]:
import sys # sys is a module in which we need a function getsizeof that tells the size of an element

In [71]:
print(sys.getsizeof(87)*len(lista)) # Here we get the size of an existing element 87 multiplying with the length of lista

2800


In [72]:
print(arr11.itemsize * arr11.size) # NumPy arrays use less memory
                                   # NumPy arrays are faster in comparison to lists

800


In [73]:
import time

In [74]:
x = range(100000)
y = range(100000,200000)

start_time = time.time()

# The zip() function in Python is a built-in utility that aggregates elements from multiple iterables (such as lists, tuples, or strings) into a single iterable of tuples

c = [x+y for x,y in zip(x,y)]   # Extracting elements from x and y, then add the elements into a list    
print(time.time() - start_time)

0.010236024856567383


In [75]:
a = np.arange(100000)
b = np.arange(100000,200000)

start_time = time.time()
c = a + b
print(time.time() - start_time)

0.0013194084167480469


In [76]:
arr12 = np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [77]:
arr12[:,2:3]  # If we want to print any column, first we should print all the rows (:,) then 
# 2:3 মানে কলাম ইনডেক্স 2 থেকে শুরু করে ইনডেক্স 3 এর আগ পর্যন্ত (অর্থাৎ শুধু ইনডেক্স 2) নির্বাচন করা।
# এখানে 3 হলো স্লাইসিং-এর শেষ বিন্দু, কিন্তু ইনডেক্স 3 এর মান বাদ যায়।

array([[ 2],
       [ 6],
       [10],
       [14],
       [18],
       [22]])

In [78]:
arr12[:,2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [79]:
arr12[2:4,1:3]  # If we want to extract 9,10,13,14 from array12

array([[ 9, 10],
       [13, 14]])

In [80]:
arr12[4:6,2:4] # arr12[4:,2:]

array([[18, 19],
       [22, 23]])

In [81]:
# Iteration
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [82]:
for i in np.nditer(arr12):   # This will not print with row
    print(i)                 # If you want to apply a filter to each pixel of an image, you should use the following logic.

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [83]:
# Operations
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])

In [84]:
arr1 - arr2

array([-3, -3, -3, -3, -3, -3])

In [85]:
arr1 * arr2  # Vector multiplication

array([ 4, 10, 18, 28, 40, 54])

In [86]:
arr1 * 2  # Scalar multiplication

array([ 2,  4,  6,  8, 10, 12])

In [87]:
arr2 > 7

array([False, False, False, False,  True,  True])

In [88]:
arr3 = np.arange(6).reshape(2,3)
arr4 = np.arange(6,12).reshape(3,2)

In [89]:
arr3.dot(arr4)  # (2 * 3).(3 * 2) = 2 * 2

array([[ 28,  31],
       [100, 112]])

In [ ]:
arr1.dot(ar3) # criteria for a dot product is not matched, so it will throw an error

NameError: name 'ar3' is not defined

In [91]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [93]:
arr4.max()

np.int64(11)

In [94]:
arr4.min()

np.int64(6)

In [95]:
arr4.min(axis = 0)  # axis = 0 means column wise minimum, axis = 1 means row wise minimum

array([6, 7])

In [96]:
arr4.min(axis = 1)

array([ 6,  8, 10])

In [97]:
arr4.sum()

np.int64(51)

In [98]:
arr4.sum(axis = 0)  # axis = 0 means column wise sum

array([24, 27])

In [99]:
arr4.mean()

np.float64(8.5)

In [100]:
arr4.std()  # Standard deviation

np.float64(1.707825127659933)

In [101]:
np.sin(arr4)  # Apply sin function to each element of arr4

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [109]:
np.median(arr4)  # Median value
                 # np.median(arr4, axis=0)  # Median value column wise
                 # np.median(arr4, axis=1)  # Median value row wise 
                 # Universal functions (ufuncs) are functions that operate element-wise on arrays, allowing for efficient computations.

np.float64(8.5)