In [4]:
import numpy as np

In [5]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [6]:
type(arr1)

numpy.ndarray

In [7]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
arr4 = np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
arr5 = np.identity((5))
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
arr6 = np.arange(1,15,2) # np.arange(5,15), np.arange(10)
arr6

array([ 1,  3,  5,  7,  9, 11, 13])

In [12]:
arr7 = np.linspace(10,20,10)
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [13]:
arr8 = np.copy(arr7)
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [14]:
arr9 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [15]:
arr9.shape


(2, 2, 2)

In [16]:
arr9.ndim

3

In [17]:
arr9.size #number of elements

8

In [18]:
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [19]:
arr9.itemsize #float -8

8

In [20]:
arr8.itemsize # size of 1 element in byte

8

In [21]:
arr9.dtype

dtype('int64')

In [22]:
arr8.dtype

dtype('float64')

In [23]:
arr9.astype('float')     # CONVERT INT to Float

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [24]:
arr9.dtype

dtype('int64')

In [25]:
lista =range(100)
arr11 = np.arange(100)

In [26]:
import sys # sys is a module in which we need a function getsizeof that tells the size of an element

In [27]:
print(sys.getsizeof(87)*len(lista)) # Here we get the size of an existing element 87 multiplying with the length of lista

2800


In [28]:
print(arr11.itemsize * arr11.size) # NumPy arrays use less memory
                                   # NumPy arrays are faster in comparison to lists

800


In [29]:
import time

In [30]:
x = range(100000)
y = range(100000,200000)

start_time = time.time()

# The zip() function in Python is a built-in utility that aggregates elements from multiple iterables (such as lists, tuples, or strings) into a single iterable of tuples

c = [x+y for x,y in zip(x,y)]   # Extracting elements from x and y, then add the elements into a list    
print(time.time() - start_time)

0.008731365203857422


In [31]:
a = np.arange(100000)
b = np.arange(100000,200000)

start_time = time.time()
c = a + b
print(time.time() - start_time)

0.0017414093017578125


In [32]:
arr12 = np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [33]:
arr12[:,2:3]  # If we want to print any column, first we should print all the rows (:,) then 
# 2:3 মানে কলাম ইনডেক্স 2 থেকে শুরু করে ইনডেক্স 3 এর আগ পর্যন্ত (অর্থাৎ শুধু ইনডেক্স 2) নির্বাচন করা।
# এখানে 3 হলো স্লাইসিং-এর শেষ বিন্দু, কিন্তু ইনডেক্স 3 এর মান বাদ যায়।

array([[ 2],
       [ 6],
       [10],
       [14],
       [18],
       [22]])

In [34]:
arr12[:,2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [35]:
arr12[2:4,1:3]  # If we want to extract 9,10,13,14 from array12

array([[ 9, 10],
       [13, 14]])

In [36]:
arr12[4:6,2:4] # arr12[4:,2:]

array([[18, 19],
       [22, 23]])

In [37]:
# Iteration
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [38]:
for i in np.nditer(arr12):   # This will not print with row
    print(i)                 # If you want to apply a filter to each pixel of an image, you should use the following logic.

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [ ]:
# Operations
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])

In [42]:
arr1 - arr2

array([-3, -3, -3, -3, -3, -3])

In [43]:
arr1 * arr2

array([ 4, 10, 18, 28, 40, 54])